version: '3.9'

services:
  dbpg:
    image: postgres
    restart: always
    shm_size: 128MB
    ports:
      - "5432:5432"
  dbredis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"